title: MineColonies Wiki
description: >- # this means to ignore newlines until "remote-theme"
  MineColonies Wiki
remote-theme: jekyll/minima
markdown: kramdown
baseurl: /
plugins:
- jekyll-seo-tag
destination: docs
baseurl: https://sqwatermark.github.io/MinecoloniesWiki/