title: 模拟殖民地Wiki
description: >- # this means to ignore newlines until "remote-theme"
  MineColonies Wiki
remote-theme: jekyll/minima
markdown: kramdown
baseurl: /
plugins:
- jekyll-seo-tag
destination: docs
baseurl: /MinecoloniesWiki